### PR TITLE
Access REST-API permissions on client-side

### PR DESCRIPTION
**Pull request by jabrandes**
This pull request is directed at the problems that while the IMIS frontend may show all possible operations (e.g. actions in patient details view), the current user may not have the required priviledge to actually use such operation (see #241).

The proposed implementation introduces a new `PermissionQueryController` REST endpoint which can be queried for whether API requests to specific paths using certain HTTP methods are allowed for the current user. This endpoint is utilized in a new `permissions` module in the frontend that provides an asynchronous `checkAllowed` function that operates with the Swagger API stub functions. In a nutshell, one may pass an array or a string-keyed map of Swagger API functions to the `checkAllowed` function and yields an array (or object with same keys) containing boolean values whether the client has sufficient privileges to call the respective API functions.

**Example:**
Send-to-Quarantine action in `PatientDetails` (included in this pull request):
```javascript
// Import
import * as permissions from '@/util/permissions'

// Inside PatientDetails component definition
data() {
   return {
      permissions: {
         sendToQuarantine: false,
      },
      ...
   }
},
...
methods: {
   async load() {
      this.permissions = await permissions.checkAllowed({
         sendToQuarantine: Api.sendToQuarantineUsingPost,
      })
      // this.permissions === {
      //    sendToQuarantine: false,  // for role DOCTOR
      //    sendToQuarantine: true,   // for role DEPARTMENT_OF_HEALTH
      // }
     ...
   },
   ...
},
```

**Caveats:**
The proposed solution in its current form only supports querying permissions enforced in the `SpringSecurityConfig`. **Checks of `@PreAuthorize` annotations are currently not respected!**

### CODE REVIEW

**Comment by LeonardKoll** [comment]
Review erledige ich am Montag.

**Comment by JonasCir** [comment]
Just out of curiosity: The idea is to make a "preflight" request to the server to check if the operation would succeed right? Permission checks are still enforced on the server, aren't they?

**Comment by JonasCir** [comment]
Or better: To see if a certain path is accessible from the client right?

Can't we just create a permission map on the server mapping user role to features/views which should be included in the client (given a certain role)?

**Comment by jabrandes** [comment]
The security enforcements of the server prevail. Like you already wrote, my approach is making a kind of preflight request, which sends a list of API paths together with the methods one wants to use on them. On the serverside, the new endpoint for permission query is asking the Spring framework's security filter chain whether access to the specified operations is allowed for the current user by security configuration, but excluding method-level security like `@PreAuthorize`. 

In my point of view, such preflight approach has the advantage that one does not need to know which roles are allowed to do what at the clientside. Instead, the client just asks the server whether the current user is entitled for performing some specific actions. Based on the server's result, the client can decide which components the user should get access to. E.g. in the example implementation, the client only needs to grant access to the 'Send to Quarantine' action in `PatientDetails` if the user is indeed permitted to perform such operation by server security.

**Comment by JonasCir** [comment]
@jabrandes Making the request after the login sounds reasonable to me :+1:

**Pull request merged**
