### PR TITLE
Fundamentals of Exposure Contact Management

### PR DESCRIPTION
**Pull request by jabrandes**
Related to issues #232, #264, #265 and #266 

This pull request ought to provide the fundamental functionality for adding and managing exposure contact information for contact chain tracing. Since the specified issues may suggest implementation with variations among each other, the implementation in this pull request has been created on a best effort basis to combine those.

**Features:**
- Backend-Model for generic infection sources, as well as exposure contacts
- REST-API for exposure contact management
- UI extension of `PatientDetails` view to include infection source data, as well as exposure contact management tooling

**What's still missing:**
- Issue #232: 
   - Registering new patients directly from exposure contact entry
   - Statistics
- Issue #264: 
   - Bulk import
   - Mark entries as inactive instead of current deletion of database entry
- Issue #265:
   - Patient location not shown in contacts' view
- Issue #266 (in addition to missing for #232): 
   - Registering infection sources other than index patients (by registering contact in index patient's details page)

**Note:**
Some byproducts of this pull request include an adaption of client-side `PatientInput` and `DateInput` components in an effort to allow more control over their wrapped components and to give them an external Prop-API like that of other standard components (e.g. direct usage of `v-decorator` on these components and extraction of `a-form-item` so that it can be set by the owning form / form group).

### CODE REVIEW

**Comment by wobkenh** [comment]
Das mit dem Mixin scheint noch nicht zu funktionieren
image

**Comment by jabrandes** [comment]
Er funktioniert grundsätzlich schon, wenn man die ganzen Typechecks vom tslinter außen vor lässt. Bei der Entwicklung mit `gradle serve` kann man ja auch Code testen der solche Typüberprüfungen nicht besteht, solange er noch dem Javascript-Linter genügt. Ich kann aber schauen, dass ich den Kram gerade gefixt bekomme.

**Comment by jabrandes** [comment]
Das mit dem gesicherten Typescript wird wohl noch dauern. Bei der Typisierung von Vue hat man scheinbar vergessen, dass man auch custom options verwenden kann.

**Comment by LeonardKoll** [comment]
Review erledige ich am Montag.

**Comment by jabrandes** [comment]
grafik

**Comment by LeonardKoll** [comment]
Für nach der Simulation habe ich folgendes Anschluss-Issue angelegt:
https://github.com/ImisDevelopers/1_011_a_infektionsfall_uebermittellung/issues/286

**Pull request merged**
